### ISSUE TITLE
PR 24 (filter fn) slows down SimpleIndexer

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/executor-simpleindexer#28]
Consider this

```python
from tempfile import TemporaryDirectory
from time import perf_counter

import numpy as np
from jina import Document, DocumentArray, Flow

DIM = 128
VERSION = "0.7"
index_docs = DocumentArray(
    [Document(embedding=np.random.rand(DIM)) for _ in range(100_000)]
)
search_docs = DocumentArray(
    [Document(embedding=np.random.rand(DIM)) for _ in range(10_000)]
)


with TemporaryDirectory() as tmpdir:
    f = Flow().add(
        uses=f'jinahub://SimpleIndexer/v{VERSION}', uses_metas={'workspace': tmpdir}
    )
    with f:
        f.index(index_docs)

        t = perf_counter()
        f.search(search_docs)
        print(perf_counter() - t)

```

Here are the results from timing
- version 0.7: 320
- version 0.6: 32

we get a 10x slowdown! And I think this scales ***quadratically*** with size (for 10x smaller data the slowdown is ~3x). Therefore, for a million documents we have a 100x slowdown - completely unacceptable.

This is due to `filter_fn` introduced in https://github.com/jina-ai/executor-simpleindexer/pull/24. I think we need to immediately revert this PR and then move filtering to index time or the like

**Comment by winstonww** [comment]
@tadejsv We are aware of the slow down when introducing this PR. But currently there's no way for us to validate the index docs since filtering cannot be done at `index` time as it does not have information such as `traversal_paths`. The original intention for this during refactoring as discussed was that `SimpleIndexer` should not be processing docs and traversing but should delegate this responsibility to Jina core.

 

>  I think we need to immediately revert this PR and then move filtering to index time or the like

I think this would very unsafe. One broken doc indexed could break the SimpleIndexer. Until we move filtering to index time, we should keep this for now.

**Comment by JoanFM** [comment]
> @tadejsv We are aware of the slow down when introducing this PR. But currently there's no way for us to validate the index docs since filtering cannot be done at `index` time as it does not have information such as `traversal_paths`. The original intention for this during refactoring as discussed was that `SimpleIndexer` should not be processing docs and traversing but should delegate this responsibility to Jina core.
> 
> > I think we need to immediately revert this PR and then move filtering to index time or the like
> 
> I think this would very unsafe. One broken doc indexed could break the SimpleIndexer. Until we move filtering to index time, we should keep this for now.

But u can do the filtering at index time urself.

**Comment by winstonww** [comment]
@tadejsv  @JoanFM  


I would like to elaborate on why I think having filtering is important and why it's not the best to immediately revert the PR without having any safeguards.

Imagine we have a flow with `Downloader` in it - a common use case. And we implement `Downloader` like the following:

```python
class Downloader(Executor):
    @requests
    def download(self, docs: DocumentArray, **kwargs):
        for doc in docs:
            try: 
                doc.convert_uri_to_buffer()
            except Exception:
                pass
```

However, URL download failure is very common problem. We can work around the problem by creating a new copy of `new_docs`,  appending only the docs with embeddings/blob/buffer and return `new_docs`. But this is not an obvious thing to do and users will forget. Performance may also be affected as a result. So it's very common for `docs` to have docs with no content/embedding when it's returned from the `Downloader` and when it is passed to `SimpleIndexer`. And this happens time after time in showcases/eaps. And without filtering this can be very dangerous. Even one invalid doc that gets added to index can break all subsequent searches.


I think the current filtering logic can be optimized and it would be great if we can move it to index time. However, when I repeated the above experiment and measured the time it takes to search 100 docs with 100000 indexed docs, the total time it takes is **2.2 seconds**.  I don't think it's unusable or "completely unacceptable", given that downloading data from a few doc uris for searching could easily take more time than that. And we usually don't need to search for 100 docs with 100000 index docs from the eaps/showcase I have worked with. I think the real case when SimpleIndexer becomes unusable is when it cannot return any search results. 

> But u can do the filtering at index time urself.

But then in this case user will need to implement a `Filter` executor every time if they use SimpleIndexer which could be mentally taxing? And if we decide to implement an external filter logic, later when we actually move the filter logic to index time inside SimpleIndexer as this is necessary, then we won't need the external filter logic anymore and will have remove it again?

Can we do better with performance? Yes absolutely. But is it worth removing all safeguards just to revert this PR? 

I am saying this is because docs with broken embedding gives us a lot of headaches in production.

**Comment by tadejsv** [comment]
>I think the current filtering logic can be optimized and it would be great if we can move it to index time. However, when I repeated the above experiment and measured the time it takes to search 100 docs with 100000 indexed docs, the total time it takes is 2.2 seconds. I don't think it's unusable or "completely unacceptable", given that downloading data from a few doc uris for searching could easily take more time than that. And we usually don't need to search for 100 docs with 100000 index docs from the eaps/showcase I have worked with. I think the real case when SimpleIndexer becomes unusable is when it cannot return any search results

You are missing the point. The total time here does not matter, I listed it only as an illustration of how much slower SimpleIndexer became. Index and search time are also not really related. Note that also SimpleIndexer is *much* slower on single requests than it is if you batch requests - but the real-life use case for search is single requests.

We care about the following: how many queries per second, with queries coming in as search requests with one document, can the indexer handle. According to the benchmarking we did, SI was already at the bottom of the list, and even for smaller sizes of the dataset it is already struggling (e.g. for 200k docs it can process 7 queries per second for embedding of dim 128, and only 2 for embedding of dim 960). For comparison - our best performing indexer (hnsw) was processing 100 queries per second with 1 million documents indexed.

Now, with filtering added SimpleIndexer is let's say 10x slower - this makes it completely unusable, nobody will want a service where you have to wait a couple of seconds for search results to appear.

So then Simpleindexer would be usable only for cases with up to 10k documents in the index. Do we want this? What about scaling? Do we want to present and promote a produce that can not scale at all?

**Comment by tadejsv** [comment]
> I am saying this is because docs with broken embedding gives us a lot of headaches in production.

Why did you not implement filtering of documents (using `new_docs`)? You say that users might forget about it - well, but you are professionals, and you seem to have thought about this a lot, if you decided that implementing filtering in SimpleIndexer was the best option. So why did you decide not to implement filtering at source - surely it would save you all the headaches that you had, and would be simpler than changing the whole infrastructure?

**Comment by JoanFM** [comment]
@winstonww ur concern is totally valid, but I think the performance degradation is big enough to not be part of default.

Have u checked the memory consumption when using filter and when not?

Could it make sense to have a cache of DAM searched for with the filter already passed? This would be invalidated at every index call but it could speed up the common case of index once search many times?

This cache could be per traversal paths and may be a good speed up at some potential memory consumption loss

**Comment by winstonww** [comment]
@tadejsv 

>  Do we want to present and promote a product that can not scale at all?

No, but we also want the product to be resilient. It's not fun to have to stop, clear the DAM and restart a service every time because of a single download failure.

>  nobody will want a service where you have to wait a couple of seconds for search results to appear

If we are searching images/3d models/audio and this is bound to happen at the moment because downloading the search data usually takes way longer.

> well, but you are professionals,

SimpleIndexer is designed for everyone to use. It is meant also for beginners who just started out their way in Jina. If performance is the priority, then obviously we can go for faster indexers. 

@JoanFM  I see your point, and will think about the alternatives suggested.

**Comment by cristianmtr** [comment]
I agree with @tadejsv that it should be the job of upstream to guarantee as much as possible that the Documents are ready to be processed / stored. 

We can also have this filter but I'd say we should make it a toggle-able feature. Like discussed [here](https://jinaai.slack.com/archives/C02AC4T8Y5T/p1635948822168400?thread_ts=1635928752.164300&cid=C02AC4T8Y5T)

**Comment by tadejsv** [comment]
@winstonww so I would still like to know - why didn't you go the way of filtering documents at source in your deployments?

**Comment by winstonww** [comment]
@cristianmtr  @tadejsv 

Aside from the inconvenience that we will have to warn community members clearly that if they wanted to use SimpleIndexer with preprocessors they built themselves they will have to ensure that all inputs provided to SimpleIndexer have to be valid otherwise it would result not just in a one-time crash but a permanent unrecoverable crash which signifies SimpleIndexer is error-prone, there are also other reasons as follows.

If we look at the executors in the Flow, most of the stateless executors and can still function correctly afterwards when they see invalid inputs. But for indexers, one invalid input can result in permanent damage. I would also argue that we want to err on the side of caution, we should be defensive at the most vulnerable stage of the pipeline. (i.e. the SimpleIndexer).

If we don't apply filtering at indexer, the current situation is that even one single uncaught exception at index/update from upstream can bring down the simple indexer permanently.  My understanding is that, each micro service should be resilient and should not be permanently brought down due to failure of other microservices. Otherwise, this becomes monolithic and services are highly coupled. If we look at most executors in the hub, we don't see something like the `new_docs` method applied to filter out invalid docs.  We also don't wrap each executor with a big `try... catch Exception` phrase to ensure no uncaught exception at all occurs (this is also dangerous and I am not suggesting we should do it).

It's always good to minimizes failure/errors upstream, but from the eaps/solutions I have worked with it may cause us trouble if we take this assumption for granted especially when component is vulnerable to permanently damage.

**Comment by cristianmtr** [comment]
> vulnerable to permanently damage.

It's only SI that can accept a doc of a diff emb shape that the existing vectors. 

So there are two problems here:

1. no embeddings present in doc

- SI will accept this, can NOT recover
- other indexers will not accept this at all BUT the entire batch operation will fail; they continue to be operational

2. wrong embedding shape

- SI will accept this, and can NOT recover
- other indexers will not accept this at all BUT the entire batch operation will fail; they continue to be operational

Am I right here? 

If so, I propose

- a filter fn to catch and remove these (True by default, that can be toggled off per request or per indexer at init time)

**Comment by winstonww** [comment]
> SI will accept this, and can NOT recover
Yes if we revert the PR
